/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principalCliente;

import com.digitalpersona.uareu.Reader;
import com.digitalpersona.uareu.ReaderCollection;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author wilmer
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    UtilidadesLector_1 utilidadesLector = new UtilidadesLector_1();
    Reader m_reader;

    public Vista() {
        initComponents();        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelContenedor = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelSubtitulo = new javax.swing.JLabel();
        jLabelNumSocio = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCapturaNombre = new javax.swing.JLabel();
        jPanelHuellaDigital = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelEsperaHuella = new javax.swing.JLabel();
        jLabelHuella = new javax.swing.JLabel();
        jTextFieldidusuario = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jButtonIniciar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSiguiente = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelContenedor.setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 36)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("USUARIO");

        jLabelSubtitulo.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
        jLabelSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSubtitulo.setText("CAPTURA HUELLA DIGITAL");

        jLabelNumSocio.setText("USUARIO:");

        jLabelNombre.setText("NOMBRE:");

        jPanelHuellaDigital.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHuellaDigital.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "HUELLA DIGITAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cap3.png"))); // NOI18N
        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanelHuellaDigitalLayout = new javax.swing.GroupLayout(jPanelHuellaDigital);
        jPanelHuellaDigital.setLayout(jPanelHuellaDigitalLayout);
        jPanelHuellaDigitalLayout.setHorizontalGroup(
            jPanelHuellaDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHuellaDigitalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        jPanelHuellaDigitalLayout.setVerticalGroup(
            jPanelHuellaDigitalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHuellaDigitalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabelEsperaHuella.setPreferredSize(new java.awt.Dimension(50, 60));

        jLabelHuella.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabelHuella.setPreferredSize(new java.awt.Dimension(80, 100));

        jTextFieldidusuario.setPreferredSize(new java.awt.Dimension(4, 22));

        jButtonBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/busqueda.png"))); // NOI18N
        jButtonBuscar.setToolTipText("Buscar");
        jButtonBuscar.setBorder(null);
        jButtonBuscar.setBorderPainted(false);

        jButtonIniciar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/iniciar.png"))); // NOI18N
        jButtonIniciar.setToolTipText("Iniciar");
        jButtonIniciar.setBorder(null);
        jButtonIniciar.setBorderPainted(false);
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/cancelar.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.setBorder(null);
        jButtonCancelar.setBorderPainted(false);

        jButtonSiguiente.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/pasar.png"))); // NOI18N
        jButtonSiguiente.setToolTipText("Siguiente");
        jButtonSiguiente.setBorder(null);
        jButtonSiguiente.setBorderPainted(false);

        jButtonActualizar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/16x16/refrescar.png"))); // NOI18N
        jButtonActualizar.setToolTipText("Actualizar");
        jButtonActualizar.setBorder(null);
        jButtonActualizar.setBorderPainted(false);

        jScrollPane.setBorder(null);

        jTextPane.setText("Seleccione el dedo a capturar de la siguiente imagen, despues coloque el dedo en el escaner para capturar la huella digital.");
        jTextPane.setFocusable(false);
        jScrollPane.setViewportView(jTextPane);

        javax.swing.GroupLayout jPanelContenedorLayout = new javax.swing.GroupLayout(jPanelContenedor);
        jPanelContenedor.setLayout(jPanelContenedorLayout);
        jPanelContenedorLayout.setHorizontalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelSubtitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(jTextFieldidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelCapturaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanelHuellaDigital, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHuella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabelEsperaHuella, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanelContenedorLayout.setVerticalGroup(
            jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelContenedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelTitulo)
                .addGap(7, 7, 7)
                .addComponent(jLabelSubtitulo)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addComponent(jLabelNumSocio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldidusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jLabelCapturaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelHuellaDigital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelContenedorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelHuella, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabelEsperaHuella, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        new Enrol(jLabelHuella);
    }//GEN-LAST:event_jButtonIniciarActionPerformed

    public ReaderCollection iniciaLector() {
        return utilidadesLector.enciendeLector();
    }

    public Reader seleccionaLector(ReaderCollection m_collection) {
        return utilidadesLector.seleccionaLector(m_collection);
    }

    public void apagaLector() {
        utilidadesLector.apagaLector();
    }

    class Enrol {

        private boolean b = false;
        private List<Object> milista;
        private Reader m_reader;

        public Enrol(JLabel jLabelCapturaHuella) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    m_reader = seleccionaLector(iniciaLector());
                    b = true;
                }
            }).start();
            try {
                while (b == false) {
                    Thread.sleep(500);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }

            System.out.println("Reader:" + m_reader);
            milista = Enrolar.Run(m_reader,jLabelCapturaHuella, jLabel6, jLabel6, WIDTH);
            if (m_reader != null) {
                try {
                    m_reader.StopStreaming();
                    System.out.println("deteniendo Stream +1");
                } catch (Exception e) {
                    System.out.println("deteniendo Stream -1");
                }
                try {
                    m_reader.CancelCapture();
                    System.out.println("deteniendo Captura +1");
                } catch (Exception e) {
                    System.out.println("deteniendo Captura -1");
                }
                try {
                    m_reader.Close();
                    System.out.println("cerrando lector +1");
                } catch (Exception e) {
                    System.out.println("cerrando lector -1");
                }
            }
            apagaLector();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonActualizar;
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonCancelar;
    public javax.swing.JButton jButtonIniciar;
    public javax.swing.JButton jButtonSiguiente;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabelCapturaNombre;
    public javax.swing.JLabel jLabelEsperaHuella;
    public javax.swing.JLabel jLabelHuella;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumSocio;
    private javax.swing.JLabel jLabelSubtitulo;
    private javax.swing.JLabel jLabelTitulo;
    public javax.swing.JPanel jPanelContenedor;
    public javax.swing.JPanel jPanelHuellaDigital;
    private javax.swing.JScrollPane jScrollPane;
    public javax.swing.JTextField jTextFieldidusuario;
    public javax.swing.JTextPane jTextPane;
    // End of variables declaration//GEN-END:variables
}
